# Generated by Django 5.1.4 on 2024-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='todo_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
