# Generated by Django 5.1.4 on 2024-12-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_train_status_train_todo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='todo_name',
            new_name='name',
        ),
    ]
